alert("datos personales");
console.log("datos personales");
let firstName;
firstName="Carlos";
console.log(firstName);
let surName;
surName="Zuñiga";
console.log(surName);
let age;
age=(19);
console.log(age);
let birth;
birth= ("sempiembre, 07 2003");
console.log(birth);
let sex;
sex=["M"];
console.log(sex);
let number;
number=0961463486;
console.log(number);
let sport;
sport=["voley","futbol","tenis"];
console.log(sport);
let student;
student=("true");
console.log(student);
let dni;
dni=(0150263200);
console.log(dni);